stages:
- build
- cleanup
- deploy

build:
  script:
    # SSH agent/key
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_DEPLOY_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    # Get submodule
    - git submodule sync
    - git submodule update --init --remote --recursive
    # Build horizon client
    - cd horizon/client
    - npm install
    - npm run compile && npm run build
    # Build ETF
    - cd ../..
    - npm install
    - NODE_ENV=production "node_modules/.bin/webpack" --config webpack.production.config.js >> output
    - if grep 'ERROR in' output; then exit 1; else echo Build success; fi
    - rm build/vendor.js.map
    - rm build/app.js.map
    - npm run build-server
  stage: build
  only:
    - master
  tags:
    - nodejs
  allow_failure: false

deploy:
  script:
    - wget -qO- https://www.distelli.com/download/client | sh
    - distelli deploy -q -y -m "Deployment from Jenkins" --env EVEForecasterProduction
  stage: deploy
  environment: production
  only:
    - master
  tags:
    - nodejs
  allow_failure: false

cleanup_build:
  stage: cleanup
  script:
  - git clean -f
  - rm -rf horizon
  when: on_failure
